### ISSUE TITLE
Loading/running model trained & saved with `keras_retinanet` (TF 1.14) using `tf_retinanet` (TF 2.0)

### ISSUE THREAD

**Issue by andriiyurkiv** [fizyr/tf-retinanet#44]
Environment:
Ubuntu:         18.04
Tensorflow     2.0

I am loading the model trained/saved using `keras_retinanet` into `tf_retinanet` with the following code:
```
from tf_retinanet import models
from tf_retinanet.utils.config import set_defaults
from tf_retinanet.backbones import get_backbone
from my_defaults import default_evaluation_config  # changed a bit default evaluation configs

from _batch_normalization import BatchNormalization # copied from keras_resnet package  

model_path = 'my_old_retinanet_model_trained_with_keras_retinanet.h5'

retinanet_config = set_defaults({}, submodels_manager = models.submodels.SubmodelsManager(retinanet_config['submodels'])
submodels_manager.create(num_classes=80)

backbone = get_backbone(retinanet_config['backbone'])
self.model = models.load_model(model_path,
                                       backbone=backbone,
                                       submodels=submodels_manager.get_submodels(),
                                       custom_objects={
                                           'BatchNormalization': BatchNormalization
                                       })
```
Model loading goes fine, so I try to make inference using the model loaded:

```
image = cv2.imread('image.png')
data = np.expand_dims(image, axis=0)
result = model.predict(tf.constant(data)) # output is the same with or without tf.constant
```
`model.predict` fails with the following error:

```
2020-03-19 17:57:13.300204: I tensorflow/core/platform/cpu_feature_guard.cc:145] This TensorFlow binary is optimized with Intel(R) MKL-DNN to use the following CPU instructions in performance critical operations:  SSE4.1 SSE4.2 AVX AVX2 FMA
To enable them in non-MKL-DNN operations, rebuild TensorFlow with the appropriate compiler flags.
2020-03-19 17:57:13.324100: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2304000000 Hz
2020-03-19 17:57:13.325293: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x560dbf0e55c0 executing computations on platform Host. Devices:
2020-03-19 17:57:13.325337: I tensorflow/compiler/xla/service/service.cc:175]   StreamExecutor device (0): Host, Default Version
2020-03-19 17:57:13.325871: I tensorflow/core/common_runtime/process_util.cc:115] Creating new thread pool with default inter op setting: 2. Tune using inter_op_parallelism_threads for best performance.
WARNING:tensorflow:No training configuration found in save file: the model was *not* compiled. Compile it manually.
2020-03-19 17:57:25.807059: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at strided_slice_op.cc:108 : Invalid argument: slice index 1 of dimension 0 out of bounds.
2020-03-19 17:57:25.807120: W tensorflow/core/common_runtime/base_collective_executor.cc:216] BaseCollectiveExecutor::StartAbort Invalid argument: slice index 1 of dimension 0 out of bounds.
         [[{{node anchors_3/strided_slice}}]]
2020-03-19 17:57:25.820325: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at strided_slice_op.cc:108 : Invalid argument: slice index 1 of dimension 0 out of bounds.
2020-03-19 17:57:25.855884: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at strided_slice_op.cc:108 : Invalid argument: slice index 1 of dimension 0 out of bounds.
2020-03-19 17:57:26.122898: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at strided_slice_op.cc:108 : Invalid argument: slice index 1 of dimension 0 out of bounds.
2020-03-19 17:57:26.124582: W tensorflow/core/framework/op_kernel.cc:1622] OP_REQUIRES failed at strided_slice_op.cc:108 : Invalid argument: slice index 1 of dimension 0 out of bounds.
Traceback (most recent call last):
  File "model_loading_test.py", line 33, in <module>
    result = model.predict(tf.constant(data))
  File "/home/andrii/miniconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training.py", line 909, in predict
    use_multiprocessing=use_multiprocessing)
  File "/home/andrii/miniconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_arrays.py", line 722, in predict
    callbacks=callbacks)
  File "/home/andrii/miniconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_core/python/keras/engine/training_arrays.py", line 393, in model_iteration
    batch_outs = f(ins_batch)
  File "/home/andrii/miniconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_core/python/keras/backend.py", line 3740, in __call__
    outputs = self._graph_fn(*converted_inputs)
  File "/home/andrii/miniconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1081, in __call__
    return self._call_impl(args, kwargs)
  File "/home/andrii/miniconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1121, in _call_impl
    return self._call_flat(args, self.captured_inputs, cancellation_manager)
  File "/home/andrii/miniconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 1224, in _call_flat
    ctx, args, cancellation_manager=cancellation_manager)
  File "/home/andrii/miniconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_core/python/eager/function.py", line 511, in call
    ctx=ctx)
  File "/home/andrii/miniconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_core/python/eager/execute.py", line 67, in quick_execute
    six.raise_from(core._status_to_exception(e.code, message), None)
  File "<string>", line 3, in raise_from
tensorflow.python.framework.errors_impl.InvalidArgumentError:  slice index 1 of dimension 0 out of bounds.
         [[node anchors_3/strided_slice (defined at /home/andrii/miniconda3/envs/tf2/lib/python3.6/site-packages/tensorflow_core/python/framework/ops.py:1751) ]] [Op:__inference_keras_scratch_graph_14306]

Function call stack:
keras_scratch_graph
```
Input shape seems to be fine. What could be the reason of this error? 

* This code was ran on CPU-only machine, but I also tried to execute it on GPU machine with similar CUDA-based environment. On that machine I got the same error.

**Comment by andriiyurkiv** [comment]
Solved the issue. You can use `keras_retinanet` in your TF2 project, but you need to have both Keras and TF2.0 installed. Keras 2.3.1 worked for me.

**Comment by vcarpani** [comment]
Hi, the weights are not compatible 1:1 we are thinking about providing a conversion script. Closing this, since you solve in another way.

**Comment by waylonflinn** [comment]
Hints on how to do the conversion? If I come up with a script I'll post a PR.

Any work you've done on this or knowledge you have would be very helpful.
